package com.aurora.client.theme;

import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

import static com.aurora.client.theme.ContrastFixtures.ACCENTS;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Byte-level semantic-token compatibility against the snapshot generated
 * from the pre-D-1 implementation at {@code a1b8f1d}. It covers all forty
 * tokens, both modes, every stress accent, both resolver paths, four window
 * opacities, and historical {@code pickOnColor} output. The new derivation
 * snapshot is intentionally absent: this resource is an old-output oracle,
 * not data generated by the implementation under test.
 */
class TokenBaselineEquivalenceTest {

    @Test
    void allPreD1TokenRowsRemainByteIdentical() throws Exception {
        List<String> lines = baselineLines();
        assertEquals(64, lines.size(), "tracked pre-D-1 baseline row count");
        for (String line : lines) {
            String[] part = line.split(" ");
            switch (part[0]) {
                case "FACTORY", "RESOLVED" -> verifyResolvedRow(part);
                case "PICK" -> verifyPickRow(part);
                default -> verifyPaletteRow(part);
            }
        }
    }

    private static void verifyPaletteRow(String[] part) {
        assertEquals(ThemeToken.values().length + 2, part.length);
        Integer accent = fixture(part[0]);
        assertNotNull(accent, "named accent fixture " + part[0]);
        int[] colors = PaletteEngine.derive(accent, ThemeMode.valueOf(part[1]));
        assertTokens(part, 2, colors, part[0] + " " + part[1]);
    }

    private static void verifyResolvedRow(String[] part) {
        assertEquals(ThemeToken.values().length + 3, part.length);
        ThemeDefinition definition = new ThemeDefinition();
        definition.mode = ThemeMode.valueOf(part[1]);
        definition.backgroundOpacity = Double.parseDouble(part[2]);
        definition.accent = ContrastFixtures.DEFAULT_RED;
        ResolvedTheme theme = ThemeResolver.resolve(definition, part[0].equals("RESOLVED"));
        int[] colors = new int[ThemeToken.values().length];
        for (ThemeToken token : ThemeToken.values()) {
            colors[token.ordinal()] = theme.color(token);
        }
        assertTokens(part, 3, colors, part[0] + " " + part[1] + " " + part[2]);
    }

    private static void verifyPickRow(String[] part) {
        assertEquals(3, part.length);
        Integer accent = fixture(part[1]);
        assertNotNull(accent, "named accent fixture " + part[1]);
        // The pre-D-1 generator deliberately held hue at 0 while sweeping
        // backings, isolating the choice boundary from candidate hue.
        assertEquals(parseArgb(part[2]), PaletteEngine.pickOnColor(accent, 0f),
                "historical pickOnColor output for " + part[1]);
    }

    private static Integer fixture(String name) {
        // The pre-D-1 generator used noun-first names for the two audit-only
        // pure hues; retain that provenance without duplicating RGB literals.
        if (name.equals("MAGENTA_PURE")) return ACCENTS.get("PURE_MAGENTA");
        if (name.equals("GREEN_PURE")) return ACCENTS.get("PURE_GREEN");
        return ACCENTS.get(name);
    }

    private static void assertTokens(String[] part, int offset, int[] actual, String row) {
        for (ThemeToken token : ThemeToken.values()) {
            int expected = parseArgb(part[offset + token.ordinal()]);
            assertEquals(expected, actual[token.ordinal()],
                    row + " token " + token);
        }
    }

    private static int parseArgb(String value) {
        return (int) Long.parseUnsignedLong(value, 16);
    }

    private static List<String> baselineLines() throws Exception {
        InputStream stream = TokenBaselineEquivalenceTest.class.getResourceAsStream(
                "/theme/d1-token-baseline.txt");
        assertNotNull(stream, "tracked baseline resource");
        try (BufferedReader reader = new BufferedReader(
                new InputStreamReader(stream, StandardCharsets.UTF_8))) {
            List<String> lines = new ArrayList<>();
            String line;
            while ((line = reader.readLine()) != null) {
                if (!line.isBlank()) lines.add(line.trim());
            }
            return lines;
        }
    }
}
